'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 11.25pt")>  _
        Public Property ResultFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("ResultFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("ResultFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 11.25pt")>  _
        Public Property DetailsFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("DetailsFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("DetailsFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 12pt")>  _
        Public Property CoverFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("CoverFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("CoverFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("154, 90")>  _
        Public Property CoverAddressPoint() As Global.System.Drawing.Point
            Get
                Return CType(Me("CoverAddressPoint"),Global.System.Drawing.Point)
            End Get
            Set
                Me("CoverAddressPoint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("36, 36")>  _
        Public Property CoverReportNoPoint() As Global.System.Drawing.Point
            Get
                Return CType(Me("CoverReportNoPoint"),Global.System.Drawing.Point)
            End Get
            Set
                Me("CoverReportNoPoint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("someone@gmail.com")>  _
        Public Property Email() As String
            Get
                Return CType(Me("Email"),String)
            End Get
            Set
                Me("Email") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("password")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gmail")>  _
        Public Property Provider() As String
            Get
                Return CType(Me("Provider"),String)
            End Get
            Set
                Me("Provider") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")>  _
        Public Property SMTP() As String
            Get
                Return CType(Me("SMTP"),String)
            End Get
            Set
                Me("SMTP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public Property Port() As String
            Get
                Return CType(Me("Port"),String)
            End Get
            Set
                Me("Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("""")>  _
        Public Property Quot() As String
            Get
                Return CType(Me("Quot"),String)
            End Get
            Set
                Me("Quot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DisplayName() As String
            Get
                Return CType(Me("DisplayName"),String)
            End Get
            Set
                Me("DisplayName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReportTop() As Integer
            Get
                Return CType(Me("ReportTop"),Integer)
            End Get
            Set
                Me("ReportTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReportBottom() As Integer
            Get
                Return CType(Me("ReportBottom"),Integer)
            End Get
            Set
                Me("ReportBottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReportLeft() As Integer
            Get
                Return CType(Me("ReportLeft"),Integer)
            End Get
            Set
                Me("ReportLeft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReportRight() As Integer
            Get
                Return CType(Me("ReportRight"),Integer)
            End Get
            Set
                Me("ReportRight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SignatureX() As Integer
            Get
                Return CType(Me("SignatureX"),Integer)
            End Get
            Set
                Me("SignatureX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SignatureY() As Integer
            Get
                Return CType(Me("SignatureY"),Integer)
            End Get
            Set
                Me("SignatureY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SignatureWidth() As Integer
            Get
                Return CType(Me("SignatureWidth"),Integer)
            End Get
            Set
                Me("SignatureWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SignatureHeight() As Integer
            Get
                Return CType(Me("SignatureHeight"),Integer)
            End Get
            Set
                Me("SignatureHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Filename() As String
            Get
                Return CType(Me("Filename"),String)
            End Get
            Set
                Me("Filename") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ImageFixedWidth() As Boolean
            Get
                Return CType(Me("ImageFixedWidth"),Boolean)
            End Get
            Set
                Me("ImageFixedWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ImageWidth() As Integer
            Get
                Return CType(Me("ImageWidth"),Integer)
            End Get
            Set
                Me("ImageWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ImageHeight() As Integer
            Get
                Return CType(Me("ImageHeight"),Integer)
            End Get
            Set
                Me("ImageHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 15.75pt, style=Bold")>  _
        Public Property StatementHeaderFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("StatementHeaderFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("StatementHeaderFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 11.25pt")>  _
        Public Property StatementFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("StatementFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("StatementFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property pageNumberLoc() As Global.System.Drawing.Point
            Get
                Return CType(Me("pageNumberLoc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("pageNumberLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 11.25pt")>  _
        Public Property pageNumberFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("pageNumberFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("pageNumberFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property StatementImage() As Integer
            Get
                Return CType(Me("StatementImage"),Integer)
            End Get
            Set
                Me("StatementImage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("71")>  _
        Public Property StatementMarginTop() As Integer
            Get
                Return CType(Me("StatementMarginTop"),Integer)
            End Get
            Set
                Me("StatementMarginTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("71")>  _
        Public Property StatementMarginBottom() As Integer
            Get
                Return CType(Me("StatementMarginBottom"),Integer)
            End Get
            Set
                Me("StatementMarginBottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("71")>  _
        Public Property StatementMarginLeft() As Integer
            Get
                Return CType(Me("StatementMarginLeft"),Integer)
            End Get
            Set
                Me("StatementMarginLeft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("71")>  _
        Public Property StatementMarginRight() As Integer
            Get
                Return CType(Me("StatementMarginRight"),Integer)
            End Get
            Set
                Me("StatementMarginRight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportNumLoc() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportNumLoc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportNumLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportDateLoc() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportDateLoc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportDateLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportNameLoc() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportNameLoc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportNameLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportAgeLoc() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportAgeLoc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportAgeLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportSexLoc() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportSexLoc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportSexLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportReferredLoc() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportReferredLoc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportReferredLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportHospitalLoc() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportHospitalLoc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportHospitalLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportReceivedDate() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportReceivedDate"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportReceivedDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportResultLoc() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportResultLoc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportResultLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1150")>  _
        Public Property StatementPageNumberY() As Integer
            Get
                Return CType(Me("StatementPageNumberY"),Integer)
            End Get
            Set
                Me("StatementPageNumberY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property EmailAddresses() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("EmailAddresses"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("EmailAddresses") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SSPLM.My.MySettings
            Get
                Return Global.SSPLM.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
