'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OMSFileBox.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property DB_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBI_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBI_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Drop_Box_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drop Box-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DB_01
        '''DB_02
        '''DB_03
        '''DB_04
        '''DB_05
        '''DB_06
        '''DB_07
        '''DB_08
        '''DB_09
        '''DB_10
        '''DB_11
        '''DB_12
        '''DB_13
        '''DB_14
        '''DB_15
        '''DB_16
        '''DB_17
        '''DB_18
        '''DB_19
        '''DB_20
        '''DB_21
        '''DB_22.
        '''</summary>
        Friend ReadOnly Property ImageNames() As String
            Get
                Return ResourceManager.GetString("ImageNames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DBI_01
        '''DBI_02
        '''DBI_03
        '''DBI_04
        '''DBI_05
        '''DBI_06
        '''DBI_07
        '''DBI_08
        '''DBI_09
        '''DBI_10
        '''DBI_11.
        '''</summary>
        Friend ReadOnly Property ImageNames2() As String
            Get
                Return ResourceManager.GetString("ImageNames2", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property User_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
