'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GlobalCode.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _100px_Eye_Black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_100px_Eye_Black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _100px_Eye_Gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_100px_Eye_Gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property A001() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("A001", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property A002() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("A002", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property A003() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("A003", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property A004() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("A004", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property B001() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("B001", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property B002() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("B002", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property B003() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("B003", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property B004() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("B004", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property C001() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("C001", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property C002() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("C002", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property C003() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("C003", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property C004() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("C004", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property D001() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("D001", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property D002() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("D002", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property D003() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("D003", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property D004() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("D004", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property FyaPV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FyaPV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Notification() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notification", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
